"""add ntfy_topic and notify_wishlist to users

Revision ID: 4f2b94bb4404
Revises: 51227e41ce2c
Create Date: 2026-06-12 12:25:40.406527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2b94bb4404'
down_revision = '51227e41ce2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ntfy_topic', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notify_wishlist', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_wishlist')
        batch_op.drop_column('ntfy_topic')

    # ### end Alembic commands ###
