"""initial migration

Revision ID: d83132f203ef
Revises: 
Create Date: 2026-06-11 17:40:34.326286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83132f203ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_caps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('style', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('images_json', sa.Text(), nullable=True),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('wishlisted', sa.Integer(), nullable=False),
    sa.Column('cap_type', sa.Text(), nullable=False),
    sa.Column('panels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('images_json', sa.Text(), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('panels', sa.Text(), nullable=True),
    sa.Column('panels_override', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Text(), nullable=False),
    sa.Column('is_limited', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'release_date')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_items',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('owned', sa.Integer(), nullable=False),
    sa.Column('wishlisted', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('preferred_size', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('variants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variants')
    op.drop_table('user_items')
    op.drop_table('snapshots')
    op.drop_table('releases')
    op.drop_table('products')
    op.drop_table('manual_caps')
    op.drop_table('alerts')
    # ### end Alembic commands ###
