"""add notification, quiet hours, and default size settings to users

Revision ID: f58dd380d17f
Revises: 4f2b94bb4404
Create Date: 2026-06-12 12:44:29.860747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58dd380d17f'
down_revision = '4f2b94bb4404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_new_products', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('quiet_hours_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiet_hours_end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_size_caps', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_size_apparel', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('default_size_apparel')
        batch_op.drop_column('default_size_caps')
        batch_op.drop_column('quiet_hours_end')
        batch_op.drop_column('quiet_hours_start')
        batch_op.drop_column('notify_new_products')

    # ### end Alembic commands ###
